"""
Retraining policy utilities.

Decides whether the observed drift is significant enough
to trigger model retraining.
"""

import pandas as pd


def should_retrain(drift_report_df, model_config=None):
    """
    Determine whether retraining should be triggered.

    Parameters
    ----------
    drift_report_df : pandas.DataFrame
        Drift report generated by detector.py.

    model_config : dict
        Configuration containing drift threshold.

    Returns
    -------
    bool
    """

    if drift_report_df is None or drift_report_df.empty:
        return False

    drift_hits = drift_report_df.get(
        "drift_detected",
        pd.Series(False, index=drift_report_df.index)
    )

    total_features = len(drift_hits)

    drifted_features = int(drift_hits.sum())

    drift_percentage = (
        drifted_features / total_features
    ) if total_features > 0 else 0

    threshold = (
        (model_config or {})
        .get("drift_detection", {})
        .get("threshold", 0.20)
    )

    print(
        f"Retraining Policy: "
        f"{drifted_features}/{total_features} features drifted "
        f"({drift_percentage:.2%})"
    )

    if drift_percentage >= threshold:
        print("Decision: Retraining Triggered\n")
        return True

    print("Decision: Continue Monitoring\n")
    return False
